# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 233a66c627f4f27f3b34bf55ebe283acc5819cc4e5ab57618e8e16032b9b9fb61e84a76f0b9d21c11f9f290b4233d217933c1b31b979583050003703c0adc793

test:
  secret_key_base: 9b55fbf71a5f60e41013c48791a7ca8b4b91184dc1e9243d935951043fc58e0cd0d069e10ae7ae091d2d3016de427227a349e2fc0f096c6243e7f5cd47c70710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
